parameters:
#    acme_demo.example.class: Acme\DemoBundle\Example

services:
#    acme_demo.example:
#        class: %acme_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
